services:
  db:
    container_name: "happy-time-be-dev-01"
    image: postgres:17-alpine
    volumes:
      - "./database/${DB_DATA_PATH}:/var/lib/postgresql:rw"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped